export const MAP_CLUSTERING_LOAD = 'MAP_CLUSTERING_LOAD';
export const MAP_CLUSTERING_FILTER = 'MAP_CLUSTERING_FILTER';
export const MAP_GET_ADDRESS_INFO = 'MAP_GET_ADDRESS_INFO';
export const MAP_SET_CENTER = 'MAP_SET_CENTER';
// MAP_DUPLICATE_POSITION