export const INFO_DIALOG_TOGGLE             = 'INFO_DIALOG_TOGGLE';
export const INFO_DIALOG_GET_DATA_START     = 'INFO_DIALOG_GET_DATA_START';
export const INFO_DIALOG_GET_DATA_SUCCESS   = 'INFO_DIALOG_GET_DATA_SUCCESS';
export const INFO_DIALOG_GET_DATA_FAIL      = 'INFO_DIALOG_GET_DATA_FAIL';