

export const WEBSQL_SEARCH_SET              = 'WEBSQL_SEARCH_SET';
export const WEBSQL_SEARCH_REMOVE           = 'WEBSQL_SEARCH_REMOVE';

export const WEBSQL_DB_CREATE               = 'WEBSQL_DB_CREATE';
export const WEBSQL_DB_LOADING              = 'WEBSQL_DB_LOADING';
export const WEBSQL_DB_ERROR_CREATE         = 'WEBSQL_DB_ERROR_CREATE';
export const WEBSQL_DB_SUCCESS_CREATE       = 'WEBSQL_DB_SUCCESS_CREATE';

// TODO: на будующее создать отдельный экшен для создания таблицы
export const WEBSQL_TABLE_CREATE            = 'WEBSQL_TABLE_CREATE';
export const WEBSQL_TABLE_LOADING           = 'WEBSQL_TABLE_LOADING';
export const WEBSQL_TABLE_ERROR_CREATE      = 'WEBSQL_TABLE_ERROR_CREATE';
export const WEBSQL_TABLE_SUCCESS_CREATE    = 'WEBSQL_TABLE_SUCCESS_CREATE';

export const WEBSQL_VERSION_DB_LOADING      = 'WEBSQL_VERSION_DB_LOADING';
export const WEBSQL_VERSION_DB_SUCCESS      = 'WEBSQL_VERSION_DB_SUCCESS';
export const WEBSQL_VERSION_DB_ERROR        = 'WEBSQL_VERSION_DB_ERROR';
export const WEBSQL_VERSION_DB_SET          = 'WEBSQL_VERSION_DB_SET';

export const WEBSQL_SEARCH                  = 'WEBSQL_SEARCH_DB';


export const WEBSQL_DOWNLOAD_DATA_LOADING   = 'WEBSQL_DOWNLOAD_DATA_LOADING';
export const WEBSQL_DOWNLOAD_DATA_SUCCESS   = 'WEBSQL_DOWNLOAD_DATA_SUCCESS';
export const WEBSQL_DOWNLOAD_DATA_ERROR     = 'WEBSQL_DOWNLOAD_DATA_ERROR';

export const WEBSQL_SET_DATA_LOADING        = 'WEBSQL_SET_DATA_LOADING';
export const WEBSQL_SET_DATA_SUCCESS        = 'WEBSQL_SET_DATA_SUCCESS';
export const WEBSQL_SET_DATA_ERROR          = 'WEBSQL_SET_DATA_ERROR';

export const WEBSQL_GET_DATA                = 'WEBSQL_GET_DATA';

export const WEBSQL_LIST_OF_PLACES_GET      = 'WEBSQL_LIST_OF_PLACES_GET';